### ISSUE TITLE
Provide multi-arch compatible images | Sign images

### ISSUE THREAD

**Issue by ggarri** [ConsenSys/orchestrate#763] opened 2021-12-03 04:49 UTC
### Summary

Provide ARM64 compatible images for Orchestrate and QKM.

### Pre-requisites

Validate solution on Apple M1 CPU. 
  
### Technical Notes

```
docker logs qkm-migration
qemu: uncaught target signal 11 (Segmentation fault) - core dumped
```

```
docker logs qkm
qemu: uncaught target signal 11 (Segmentation fault) - core dumped
```

## Business Value
Avoid adoption problems for Apple M1 users.

### Acceptance Criteria

- [x] Build single image using https://docs.docker.com/buildx/working-with-buildx/
- [x] Sign docker images https://github.com/ConsenSys/ethsigner/pull/404/files

## Additional context
Two member of Summo team are experiencing the issue. Ask for more details to @Dzejkop or @jpnovais

**Comment by julien-marchand** [comment] 2021-12-13 08:20
Duplicate of #428

**Comment by ggarri** [comment] 2021-12-20 11:28
https://www.docker.com/blog/multi-arch-build-and-images-the-simple-way/

**Comment by ggarri** [comment] 2021-12-22 05:38
There is an identified inconvenient about using buildx + docker trust https://github.com/docker/buildx/issues/313

**Comment by ggarri** [comment] 2021-12-24 15:14
## Conclusions
- `docker trust` is not compatible with using `buildx`
- Buildx does not support local storage of multi arch manifest, therefore images must be push right after are generated using buildx
- Proposed alternatives is to create manifest manually using `docker manifest` which is an experimental feature and sign it using `notary` which is a low level signing tool for docker
- Notary does not have specific documentation about signing docker manifests
- Notary appears to not identify repository signers and requesting to sign images using ONLY repository root key
- Notary fails to push images to dockerhub when there are multiple images SHA

## Sources
- https://github.com/sudo-bot/action-docker-sign
- https://github.com/docker/buildx/issues/313

**Comment by ggarri** [comment] 2022-01-21 06:14
Follow up on thread
https://consensys.slack.com/archives/CC4UR01NG/p1641224723228400

**Comment by ggarri** [comment] 2022-05-27 15:40
The target of this issue it is to provide a single image manifest encapsulating both supported archs

**Closed** 2022-06-28 14:18 UTC
Labels: S: Ease of use, Won't fix
